### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by AndyReifman** [hassio-addons/addon-overseerr#15]
# Problem

Recently I've started hitting an `Internal Server Error` webpage every time I try to navigate to the Overseerr web ui

## Expected behavior

Overseerr UI to load

## Actual behavior

White page with `Internal Server Error` displayed

Looking in the logs, this is the message outputted when I try to open the web page

```
AxiosError: connect ECONNREFUSED ::1:5055
    at AxiosError.from (file:///opt/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///opt/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/opt/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  port: 5055,
  address: '::1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -111,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.3.4',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'http://localhost:5055/api/v1/settings/public',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/api/v1/settings/public',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '5055',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/api/v1/settings/public'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/v1/settings/public HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.3.4\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:5055\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/v1/settings/public',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:5055/api/v1/settings/public',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ::1:5055
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5055
  }
}
```

**Comment by sinclairpaul** [comment]
If possible could you try disabling IPV6 and retrying, as it looks to be an upstream issue relating to it.

**Comment by AndyReifman** [comment]
> If possible could you try disabling IPV6 and retrying, as it looks to be an upstream issue relating to it.

Disable on HA, Plex Server, or the entire home network?

**Comment by sinclairpaul** [comment]
Just on the HA install, so the addon cannot bind to it.

**Comment by AndyReifman** [comment]
Hmm, so I disabled IPv6, rebooted HA, and it looks like I'm still getting the same error.

I can hit `url: 'http://localhost:5055/api/v1/settings/public'` from my computer (using the correct HA url of course), but I'm not sure that's helpful.

**Comment by sinclairpaul** [comment]
Problem is ``` cause: Error: connect ECONNREFUSED ::1:5055```

Which looks to be related to <https://github.com/sct/overseerr/pull/3839>

**Comment by AndyReifman** [comment]
> lmiklosko commented Apr 5, 2024

Oof.

Wonder why I'm just now hitting this.

**Comment by Chefski** [comment]
Have you found any fix? I'm having the same problem

**Comment by SirJohnDoe** [comment]
Still happens. The addon in Alexbelgiums repo works fine (same version).

**Comment by mwilky** [comment]
> If possible could you try disabling IPV6 and retrying, as it looks to be an upstream issue relating to it.

Disabled IPv6 and still got the same issue

**Comment by AndyReifman** [comment]
I was still hitting this.

Switched to https://github.com/alexbelgium/hassio-addons/tree/master/overseerr yesterday and it appears to be working fine.

**Comment by gbcatrinoiu** [comment]
> I was still hitting this.
> 
> Switched to https://github.com/alexbelgium/hassio-addons/tree/master/overseerr yesterday and it appears to be working fine.

good suggestion works fine for me too although I don't get why. it is basically the same version

**Comment by TheS1ngularity** [comment]
I'm having the same issue. No fix yet?

**Comment by AndrewVos** [comment]
Same issue for me.

**Comment by Chefski** [comment]
@AndrewVos 
I've moved over to Jellyseerr now if you'd want to see if that helps. Works fine, seems the same, just name is different: https://github.com/alexbelgium/hassio-addons/tree/master/jellyseerr

**Comment by HydrelioxGitHub** [comment]
Anything to try with this issue ?
It seems that this issues had already been asked for a solution https://github.com/hassio-addons/addon-overseerr/issues/14 but has been closed because of stale.

**Comment by HydrelioxGitHub** [comment]
This is still happening. Does I have to provide more useful data about it ?

**Comment by HydrelioxGitHub** [comment]
This is still an issue as far as I know.

**Comment by AndrewVos** [comment]
Yeah still an issue

**Comment by maverick-79** [comment]
I'm also getting this. Do you need more information than was already provided?

**Comment by mdrodge** [comment]
installed, got error, disabled ipv6, restarted still getting error

see log

[a0d7b954_overseerr_2025-02-02T21-36-28.757Z.log](https://github.com/user-attachments/files/18634064/a0d7b954_overseerr_2025-02-02T21-36-28.757Z.log)

**Comment by AndrewVos** [comment]
This issue is not stale, bot.

**Comment by mdrodge** [comment]
Switch to the version mentioned above. It worked for me.

**Comment by CatShadow** [comment]
I have the same error, did anyone find a solution?

**Comment by techexplorers123** [comment]
the issue is still there. IPv6 is disabled
